# Generated by Django 2.0.5 on 2018-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenstoragemodel',
            name='unassigned_tokens',
        ),
        migrations.AddField(
            model_name='tokenstoragemodel',
            name='token',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
