# Generated by Django 2.0.5 on 2018-06-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180601_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tokenStorageModel',
            new_name='InvitationToken',
        ),
    ]
