# Generated by Django 2.0.5 on 2018-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180601_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
