# Generated by Django 2.0.5 on 2018-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180601_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
