# Generated by Django 2.0.5 on 2018-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invitationtoken_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
