# Generated by Django 2.0.5 on 2018-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180604_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='addon_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
