# Generated by Django 2.0.8 on 2018-10-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puffer', '0006_grafanasnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('request_date', models.DateTimeField(verbose_name='date requested')),
            ],
        ),
    ]
