# Generated by Django 2.1.2 on 2018-12-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puffer', '0007_participate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
